### ISSUE TITLE
Opening Downloaded HTML Files

### ISSUE THREAD

**Issue by l-k22** [pichillilorenzo/flutter_inappbrowser#12]
Hello, I have an epub which is downloaded to the user's device, the HTML files are extracted into a folder within the applications directory. The examples provided only refer to files being located inside the assets folder. How can I display files downloaded elsewhere?

Thanks.

**Comment by pichillilorenzo** [comment]
To get files outside an App, you can use the [path_provider](https://pub.dartlang.org/packages/path_provider) plugin and then call the [getExternalStorageDirectory](https://pub.dartlang.org/documentation/path_provider/latest/path_provider/getExternalStorageDirectory.html) function. You get the HTML string of the file and then call `openData` method (available from version **0.5.5** of my plugin) in case you are using the `InAppBrowser` class or use the `initialData` property (available from version **0.5.5** of my plugin) for the `InAppWebView` widget.
The problem is that **this will work only on Android**. Like said in the docs of the getExternalStorageDirectory function:

> Path to a directory where the application may access top level storage. The current operating system should be determined before issuing this function call, as this functionality is only available on Android.
> 
> On iOS, this function throws an UnsupportedError as it is not possible to access outside the app's sandbox.
> 
> On Android this returns getExternalStorageDirectory.

On iOS you can't access outside the app's sandbox!

So, you need a way to put the file that you want show in the App "directory" in order to make it work in a cross-platform way.

**Comment by l-k22** [comment]
Okay thank you for the quick reply.

**Comment by pichillilorenzo** [comment]
Ok! 
> Scrolling feels very sluggish though.

I think that happens because, like said in the [AndroidView](https://docs.flutter.io/flutter/widgets/AndroidView-class.html) documentation:

> Embedding Android views is an expensive operation and should be avoided when a Flutter equivalent is possible.

The support for Android native views is not full stable yet unfortunately.

**Comment by l-k22** [comment]
Could I ask for a feature request? I'm trying to figure out this myself but it's beyond my knowledge. Would it be possible to add the ability to restrict web content to the height of the container then override the swipe gesture used for back and forward to act as the next page of the split content, similar to an ebook?

thanks
