### ISSUE TITLE
Can you mark this package as discontinued?

### ISSUE THREAD

**Issue by jdnichollsc** [pichillilorenzo/flutter_inappbrowser#2]
Hello mate

Do you know if I can use this name to publish my flutter package?

**Comment by jdnichollsc** [comment]
Oh it looks like you can transfer this package to another publisher: https://dart.dev/tools/pub/publishing#transferring-a-package-to-a-verified-publisher

I want to migrate my native plugin to flutter ecosystem:
- https://github.com/proyecto26/react-native-inappbrowser
- https://github.com/proyecto26/nativescript-inappbrowser

Let me know if this looks good to you, my email is `jdnichollsc@gmail.com`
This is the publisher registered https://pub.dev/publishers/proyecto26.com/

Thanks in advance!

**Comment by pichillilorenzo** [comment]
I'm maintaining this package for old links of articles/comments/etc that were pointing to my library, so I'm sorry but I can't.
The `flutter_inappwebview` plugin, which is the new version of the `flutter_inappbrowser` plugin, has been renamed this way because it has, other than In-app native browser and `Chrome Custom Tabs/SFSafariViewController`, also inline WebView flutter widget.

**Comment by pichillilorenzo** [comment]
However, I think you can simply create a new flutter package called `flutter-inappbrowser` using the `-` (dash) instead of `_` (underscore) symbol.

**Comment by jdnichollsc** [comment]
I understand, thanks for the suggestion!
