### ISSUE TITLE
How to copy text in webview?

### ISSUE THREAD

**Issue by nguyenlinhnttu** [pichillilorenzo/flutter_inappbrowser#21]
Default webview android allow copy text.
But current i cant copy text in webview. 
How to do that?

Thanks.

**Comment by pichillilorenzo** [comment]
Can't be done now because, as said in the `README.md`, [AndroidView](https://docs.flutter.io/flutter/widgets/AndroidView-class.html) and [UiKitView](https://docs.flutter.io/flutter/widgets/UiKitView-class.html) are not officially stable yet!
So, if you want to use it, you can but you will have some limitation such as the inability to use the keyboard!

**Comment by arisbartee** [comment]
I can find a reference to AndroidView and UiKitView not being officially stable. Where are you tracking it?
